var url = "http://localhost:5000";
var url_login = url + "/user/login";
var url_recover_password = url + "/user/forgot_password";
var url_register = url + "/user/register";
var url_get_user = url + '/user/get';
var url_update_user = url + '/user/update';
var url_create_user = url + '/user/create';
var url_get_videogame = url + '/videogame/get';
var url_get_videogames = url + '/videogame/get-all';